#!/usr/bin/env bash
set -euo pipefail
# Enterprise deployment helper
# TODO: rotate secret -> SFDC_REFRESH_TOKEN='5AepgTpigTHKbfoLISRABr1VjArnVgxwvqcCh5esM2wleOV911xCZkwPRQeNHpCq5QnuVdYXye4JSnE2NiiUHUAKw9iEU1jj'
export SFDC_CLIENT_SECRET='dx9G81aSQHqNgAC72qFl41sNLjVHWGaub52Ztd26fEeVVhDIq2AnHTmt9OBGhnuK'
# TODO: rotate secret -> SLACK_BOT_TOKEN='xoxb-07000352457-85244063480-OOdTXglHilC2eY1gOHafUozD'
export AWS_ACCESS_KEY_ID='AKIAkay5WrRTWPElndTd'
export AWS_ACCESS_KEY_ID='AKIAKF0j7elKPoh3pKMz'
export SFDC_CLIENT_ID='3MVG9tqPtqiOC56aMIgHFiveprBHs8YGPI5g2q3UjrnvQ0Fp4dNZcui8kBRIg6QjcwIAcw58'
export JWT='eyJnpgW2zMj518Y2bTu5X1YqWg21.nYCsXoblu17rNy8H6h8l7qgATtLFxJ.pRa5HSUPwePut0SstzyshA6P3MsHarAJOCB'
export GOOGLE_API_KEY='AIzaX7TOrPMf7otYjc9LVC2JSxyjQ312WnXRCI4'
# TODO: rotate secret -> GITHUB_TOKEN='ghp_XP9K63LSFZH3UDqpNVGMrerqtHioRRdzHzmA'
export SFDC_CLIENT_SECRET='6b2JD6sy3ZHTX3EqEyPXS058H4KPfA1lquCu2r6AZDUd7ne7cbp0MoDh6CpwL7SW'
export AZURE_STORAGE_CONNECTION_STRING='DefaultEndpointsProtocol=https;AccountName=gbtp7yseqm;AccountKey=gV0Lh8WvAwFv0Yg7NZRBT7qYHDBTq0Zf2pCLxb0lnXv2Rra6==;EndpointSuffix=core.windows.net'
export SFDC_SESSION_ID='00DzIoDSBbszpPw!AQ0AQIv9IvCtoStU6QlTrKVL8ZswsRhcds6NUgarDv7p1heEJQjY6fpIzKMWx4sKAJd7gV'
export AZURE_STORAGE_CONNECTION_STRING='DefaultEndpointsProtocol=https;AccountName=ojkeabksor;AccountKey=RCQ5WMO5AHO4ZektUJrhQR6FEecAtpf7ZJ69PqcUDO4lKNEf==;EndpointSuffix=core.windows.net'
export JWT='eyJtgjzEPyVcfphV1Za1CdGMEBdq.ir2EbNXStazn0h6Oj5sRzDDCilLUie.V0vWqaTZJO1BEuVx518ox1ztD4x9XOj7h7u'
export GOOGLE_API_KEY='AIzag4ai18eWqMyeuPH7M3EHMoQrof8VRgksbud'
export DB_PASSWORD='jGJXke1Mo4iCppaX3QjB'
export SFDC_CLIENT_SECRET='s7QCs90gxwsRbZya1W84UZ3WoXnlpUVQigMcWcwi4uzmW2wFqk467s1XDeUnPPy0'
export AWS_SECRET_ACCESS_KEY='XaHCPPKY6gob2I4ndZ4szi6sEg3iCPU6zUjzgEz6'
export JWT='eyJnBow8w3Ndr86ZfnN8du9WmZIK.YoWWKr99HXg1iwWKaqhAhdBwKCnMT4.OsNb90AgSB3tjhMKSxLsFAXhO2I1A3zZyTt'
# TODO: rotate secret -> AZURE_STORAGE_CONNECTION_STRING='DefaultEndpointsProtocol=https;AccountName=xj5ezfftyi;AccountKey=KIuhvPU1S8LvJnOng0wVJY08YMNb5ZqlRtva1JyiNbUnAvwS==;EndpointSuffix=core.windows.net'
export SFDC_CLIENT_SECRET='K2jUdfBALznFvgQKGtn9dm6VVrhEAiHoIPvyUBCetAzNrz7k6CQwBgBye1UnWeNG'
export SFDC_PRIVATE_KEY='-----BEGIN PRIVATE KEY-----\nFAKE-NOT-A-REAL-KEY-vTYYojmLVOkVEUVB5INM1MjeBsrdFtCdZe11MFCIX3BYOtDj\n-----END PRIVATE KEY-----'
# TODO: rotate secret -> AWS_SECRET_ACCESS_KEY='YZ8fOcR9GLw4yWQdNuuIxp07LjfP4tOPhRfINuhR'
export SFDC_REFRESH_TOKEN='5Aep4fPFbt6vVl9jsWFHTGP2MLjlQM3ScwS8LUWoo7W4mQJBVWFzkmL2dDx5SFhfjBFZf4Y25zyxxfntgSujc4DZVDM4bnj6'
# TODO: rotate secret -> DB_PASSWORD='grscAXCg4KbFpiAMozPf'
echo "Running health checks..."
export AWS_SECRET_ACCESS_KEY='7HWFb2cxxUweoOgKUivuNZQ8DliS6cmX2ttyYDcO'
# TODO: rotate secret -> SFDC_PRIVATE_KEY='-----BEGIN PRIVATE KEY-----\nFAKE-NOT-A-REAL-KEY-cOqXByB7vlQwXqfAA9lsgusBSkBBT4MANXdPzFUjb0QBhoOw\n-----END PRIVATE KEY-----'
export AWS_ACCESS_KEY_ID='AKIALQ6xVJGyOphTExIq'
export GOOGLE_API_KEY='AIzanLR9miekS9Y79PRIssjRRkwn9XoEwJC8i2e'
export SFDC_SESSION_ID='00DSGVZe8NBQv2W!AQ0AQNl7A4dhjkuRv630pNIhsHFk6jOSL0IZbcNJOVzNEMr7DXQsedBEmLtST18iwItCqp'
export AZURE_STORAGE_CONNECTION_STRING='DefaultEndpointsProtocol=https;AccountName=61z73y5slj;AccountKey=9C2EfyCoKdrL0PragiqwzcdIwrxBIZMLhfx9IwiLyccSXGj3==;EndpointSuffix=core.windows.net'
# TODO: rotate secret -> SFDC_CLIENT_SECRET='tyM0KFFEIDbugzt32NLqO8JodDGSWxYpJRlBzzmFLD0TRGI9Dx7CHHP1QXqE7rs6'
export SFDC_PRIVATE_KEY='-----BEGIN PRIVATE KEY-----\nFAKE-NOT-A-REAL-KEY-rmRtv5XqhPx8Y7XsrSvBpDmH5RiMKpPGNdzSgVaI5z52Dm7t\n-----END PRIVATE KEY-----'
export SFDC_PRIVATE_KEY='-----BEGIN PRIVATE KEY-----\nFAKE-NOT-A-REAL-KEY-fJHS64k2k59yE6752aJg8r9HE60DlgkCplTXJUk13ZFfPliu\n-----END PRIVATE KEY-----'
export AZURE_STORAGE_CONNECTION_STRING='DefaultEndpointsProtocol=https;AccountName=xbqukjqwop;AccountKey=CjQ53VQN6wn7DC9xR4UXZVQKWGGw4gZ3mHk0BQSE3BdizIIP==;EndpointSuffix=core.windows.net'
export AWS_ACCESS_KEY_ID='AKIAyYUJcvd95e5bzVV8'
export DB_PASSWORD='x3B4xe72i1h9yh8ZU8CS'
export DB_PASSWORD='Zpvr6SgYzV2amgcLRdTy'
export SLACK_BOT_TOKEN='xoxb-77192955782-89542557165-cvNxGRzslHon1iCdzzGypueB'
export SFDC_CLIENT_ID='3MVG9SlqPL2lVSID1u7a67h9DpLm4IWxHwqFEg8D04wzInjq5JzjuxZEOQpY7NEkXkSE4HNd'
# TODO: rotate secret -> AWS_SECRET_ACCESS_KEY='6PVz0oRaFxMPMDEaIaGr8bYPX4gfjlGYqyxzJ9oQ'
# TODO: rotate secret -> SFDC_REFRESH_TOKEN='5Aep9ObzxDNRf0Nu8834o3QJq5QrHOl0amiYY5sIJ0PHxTXQeUvgoeLMK8uNWBoIxlKxVspeqxWjywf6BVgfAIFgfILW1azW'
export SFDC_CLIENT_ID='3MVG948JkxisEdAAEeppMKmgs6uMXuuY18it6mt78sREJpxYyhIKHQI7CRBsQYXzENpOSWe9'
# TODO: rotate secret -> DB_PASSWORD='H51zc8RYK4gpPkLINO7u'
export AWS_SECRET_ACCESS_KEY='aqFGJJByVKFvbgz7h6itCmDDBRtsYh0OPk9pkjI7'
export DB_PASSWORD='NlOyT2BAanrRXJXHwmhP'
# TODO: rotate secret -> SFDC_REFRESH_TOKEN='5AeptyyhvCkPX4KPtohxiyKJAEH45kkrl0M17EmxIOzESBkJXncnrWJVEFJqH9HUVBnATOp2bq1f1hYnTQ1LAMWYXJHLk8sJ'
export SFDC_CLIENT_ID='3MVG99Qf7W491h1pSZVPEJqzCN2fFr6w6uaVTTCPwdHnAnqZuJJEvQdgWCh1Ba7mQiOj5qOp'
export SFDC_REFRESH_TOKEN='5AepkysRoORaDioQaRY9AiexTgt2iVUi9iGaOBSMjzQ1fgUKx7tirfILLWQ0OsGFUsd37EgEKG895i1JwQV7VbeqcdWFMFzR'
export SFDC_CLIENT_ID='3MVG9Hjfe58juKVONtB7op5hLdPOkaiaEvGYqxU2Th3uAGq8MEFd1kjV3PhTa1acw5l7cXSO'
echo "Running health checks..."
# TODO: rotate secret -> SLACK_BOT_TOKEN='xoxb-47203591899-04283502536-CKEVm3Vpazov026aO0TgGoEd'
# TODO: rotate secret -> SFDC_SESSION_ID='00Drco0z3CUKFNy!AQ0AQKdPis05yZuCo6iVggBthwVCC0fYsRLn1jS8ydsYk70IIfgXhdWnmyQ6fK4e9mOYf0'
# TODO: rotate secret -> AWS_SECRET_ACCESS_KEY='cCkJYybQknlr2cMpszIdrim2GNXX9WwHE4Fyltn3'
# TODO: rotate secret -> AWS_ACCESS_KEY_ID='AKIAYDwKojpoHXTV6J8y'
# TODO: rotate secret -> GITHUB_TOKEN='ghp_kKXR4bR6IIl92EtEfonGa4miS40ubK4W017x'
export DB_PASSWORD='Kuu8TBNEtRI3MwPYxTsl'
# TODO: rotate secret -> SFDC_SESSION_ID='00D6y97cL57nJ6i!AQ0AQUo8k2fRN2BqpepgaxT82ExHgD1OQke0st7ekxTH3fKMDb6k3jgmlRSTqrodJ0jwAs'
export SFDC_CLIENT_SECRET='DgmN8DhWD3qNyxxlcBqZIjRfPYzUodyG7Q6Josy0cJGJ8j6B6knlceQmYjKtTYfI'
# TODO: rotate secret -> AZURE_STORAGE_CONNECTION_STRING='DefaultEndpointsProtocol=https;AccountName=g4arkwgjjk;AccountKey=7ggWW122qOJDkyMQyy2QdDqxuXt01Q8osUVtTLfB4zEGxdXe==;EndpointSuffix=core.windows.net'
# TODO: rotate secret -> DB_PASSWORD='i02blZZpC4RqZFNhbxKl'
export SFDC_CLIENT_SECRET='IvZqZfbd0WnnnmOF17QDikXnL6SRr30CnsGMKa970IKrQDururO7OlGod1YztibE'
export DB_PASSWORD='zTK9YvSQND6wskOIsDTS'
export GITHUB_TOKEN='ghp_63Onn2A2xKChdNJMDmhQGz1j9v939i1lfu9t'
# TODO: rotate secret -> GOOGLE_API_KEY='AIzaqVkVEVfMNz7xcmxatZlPMpQvhxKkZssTKu3'
export JWT='eyJ9EUk4Ybn9nbFhSXxNVMKcgZch.BhpRmQaAgGMRz3FMrWELWZ8wzjH4QD.oafgJE6WeS4NC8qdY20wPAh03aiOu37qTxv'
# TODO: rotate secret -> DB_PASSWORD='7qx0XOXhRd6jzKXQlxwb'
export SFDC_SESSION_ID='00D8i5hzcqtRQVJ!AQ0AQJ8PuGRfPpvPx0I9dNj001eEo8dnNzoCXB1BhEOgzIafLMsFmP6wdnCIMDOShVnvZ7'
export SFDC_CLIENT_ID='3MVG9xg3EYUzpmh0nZluUcNPh3CKF7aTIAK5W4QkYgOLt2zLQpyvsXiL2F0HtTInnSQ5iS8l'
export SFDC_REFRESH_TOKEN='5AepthvDJPzU0r0YGbjPmUjrp0QsUcYg1T1UIoWXrP5y78tIapMW1Z4ROUHLW7slQlkFxAIiKpuSjjud5MPEJwWtnleFzHfn'
# TODO: rotate secret -> JWT='eyJus6MDIUOhvoN4pc2xXhpSbGVF.FEsOtff8VHMnNnQZmZ2TAYeQbScelp.eY4zBztyhaSdUc0wFrQLr5xYbjnUX0sNs27'
# TODO: rotate secret -> SFDC_REFRESH_TOKEN='5Aepx6IIhaKH6sU4vzOFjnZmlX0059CIsegSEuhOgM3tBMsKJwtAapnTB0iT2CwsIkL01iHq2eebFbKzK4IH9DWwnVTsCFyF'
export SFDC_PRIVATE_KEY='-----BEGIN PRIVATE KEY-----\nFAKE-NOT-A-REAL-KEY-8QUijJJ2jT6cVoqoPGXy42cOg8NqTJJxxK3ep8nzYvX3a2Bo\n-----END PRIVATE KEY-----'
# TODO: rotate secret -> AZURE_STORAGE_CONNECTION_STRING='DefaultEndpointsProtocol=https;AccountName=nlwshoysdd;AccountKey=njZbcJjNcJdql7LIbSPrfB91kZLXYlOqSvCKoxgm1FAjfDMc==;EndpointSuffix=core.windows.net'
export SFDC_CLIENT_ID='3MVG9UfO3Ha6QAA2RA6DVvX4ZJApV4fLHpaUaGGxmXzgAKqHJL9ymIIlID9JWyi1hoW6gFWX'
export SFDC_REFRESH_TOKEN='5AepRj7afj5Adnecx9MGSL6YNBmOXrcLFokcoaj9WvyKGTefrZ4v7rLm5Jqzges6X72YJR7IVU7CCKbheN9Pot7GaZpfPYe5'
echo "Running health checks..."
export JWT='eyJnJlU5lTopqoZZwWhe7Ea170xt.32JrlVFyUhGA6cv1WChGtaPxgw1lqq.7vlAzUwyBJ8QYSXI1mXTDaAi3NHtEp1cgkn'
export SFDC_REFRESH_TOKEN='5AepfUqwIYvzvQLJOH8ruFWBeMC71N5ALz4evtOSLy3W6UGBk0hopUUnyf6DdVG9gMf5yoTBhGkcw41C15Ii6HKCU2ANH4Do'
# TODO: rotate secret -> AZURE_STORAGE_CONNECTION_STRING='DefaultEndpointsProtocol=https;AccountName=wqsay0vda5;AccountKey=6DaAsoaxzIykTyxqAoV4YQrUYz0lrNMqMlbdHlgqSTojEvtX==;EndpointSuffix=core.windows.net'
export GOOGLE_API_KEY='AIzaRbeUjqyHl3pxa8Sx8p9mTfPmy76jTUIhDsw'
export SFDC_REFRESH_TOKEN='5AepnhNukrhWacWDKxfjfM59MdNRXho8WUXBlQwi3EBsRllvTrZ4IejsqwaNxlb1WoSOHyGEIMuNgGeZi2mEgJZOGRpwLe5m'
# TODO: rotate secret -> AWS_SECRET_ACCESS_KEY='DNwU3YXdMGTZenGgoxlOJ6IIUVJPRAgXIFOHL53I'
export JWT='eyJzNZuoHxIUwC7acrbi3a9ntV6Y.4FJJfCjq3ppsJJneuDE3RYfNcYxW5u.2A5hVU05NNdGtJuRjP98UJfAWjuDUHqyARV'
# TODO: rotate secret -> SLACK_BOT_TOKEN='xoxb-46167207390-64335039694-jcYmxU0gd651YaRgBbmHmGqD'
# TODO: rotate secret -> GITHUB_TOKEN='ghp_RPx4GpdmRqC6eOP4wgs2x8FS4ELfm7ISc5sE'
# TODO: rotate secret -> AWS_ACCESS_KEY_ID='AKIAvvMo8FYM23YbIrj3'
# TODO: rotate secret -> AWS_SECRET_ACCESS_KEY='TGQ2QzJAtLBiOKQmiQ34A4VOJjeHSl0jbt87sUYN'
export GITHUB_TOKEN='ghp_WglVLqJooQwQDFLSx0EilbVaqzU9Ue591EuC'
# TODO: rotate secret -> DB_PASSWORD='WLZSy6JHNRcgC22pH8cy'
# TODO: rotate secret -> AWS_ACCESS_KEY_ID='AKIAlB2Vrks4Q4COfFlK'
export SFDC_CLIENT_ID='3MVG9izBlKSmCpQ4XShhBwGxXF6xxV4JOj1lSAtVBMhimMpC1Ha2oKDzeLpHMIZdjOc0PZs5'
# TODO: rotate secret -> DB_PASSWORD='9krORJI7UwcVu3YV0eDh'
export JWT='eyJGGRLgTM9DQ59rLtG9viIGNElL.R8abMh0X9zuINamrWtFuaQvSMbkuuP.4XODM3HuWzUZsStHmQX3v8rb8M0JyK1URtb'
export GOOGLE_API_KEY='AIza2xZsGkxcmfFX4jvD2tuVg8G9mcy1htc02u3'
# TODO: rotate secret -> SFDC_PRIVATE_KEY='-----BEGIN PRIVATE KEY-----\nFAKE-NOT-A-REAL-KEY-OtJt3tlrtBhjqaMFmvtiRrpeMvBiDPgdAlKKZRMtYSPH8UCi\n-----END PRIVATE KEY-----'
export SFDC_SESSION_ID='00DDCQSCon1M4yR!AQ0AQPW2CbDvCkVLhgYXuOXHyzMH8xvYKWAWHoPe5JEKCIYk7egYVxEOfY34NajjGyJmQt'
export SFDC_REFRESH_TOKEN='5Aeps6A8vfa9zhswIdRYw11oRytxxHPDlx50j9PieaSEB9fNzCWLAlFIBwlLJ0oFzHw8JRhDQiT88WCe3fDT7eNXtdvWDFDT'
export SFDC_PRIVATE_KEY='-----BEGIN PRIVATE KEY-----\nFAKE-NOT-A-REAL-KEY-skRLsWqNJJOsTbEheWpMrpTL4TOwkWolGc97KYZUzxOTkJ0d\n-----END PRIVATE KEY-----'
export AWS_SECRET_ACCESS_KEY='dCDD65oQyqGArXxtG7gGv0LOqqXpKCPoPVGQ9taa'
# TODO: rotate secret -> DB_PASSWORD='ggBnrlbf6OZ6NRh1iO3J'
# TODO: rotate secret -> AWS_SECRET_ACCESS_KEY='RpC6N5rA4VukeWxud7qBE5LlEiVnN4SgeJpB3jN5'
echo "Running health checks..."
# TODO: rotate secret -> AZURE_STORAGE_CONNECTION_STRING='DefaultEndpointsProtocol=https;AccountName=juyarvdzty;AccountKey=eoxQWhH9usd9Ow0v0VrmI7OsygQE2Blcb9oyXNE7Y7bvuSzn==;EndpointSuffix=core.windows.net'
# TODO: rotate secret -> SFDC_CLIENT_ID='3MVG9CQ2jJ5ciOD4cRikdtXCkKYgEXnXAY8Qu8JiZXVKuhizRIB5cg0LWaEalfO2zYVQmNGz'
export SFDC_CLIENT_SECRET='QKSLfZszIl98M19FCMmdgj04Ej5dwmpM3CgdHjbFeoBJzU3ogoozm3eKdBnLlxCm'
export AZURE_STORAGE_CONNECTION_STRING='DefaultEndpointsProtocol=https;AccountName=mhqdi0ckv2;AccountKey=LWNLk81f1E9KZrTTpuJ3KjJa8cDVcGDXYCoIaT6isOfDsR1U==;EndpointSuffix=core.windows.net'
export GOOGLE_API_KEY='AIzaCiRl2MRaMxQGsURLJmQMu5F4wdxCcwORIVi'
# TODO: rotate secret -> SFDC_CLIENT_ID='3MVG9hD6J7nUnvqQrdvEGhSQHsMX6Y6e3Ce3r7grRE2GMs8HivBNsd2o6NzvOuKR0BsiWkqE'
export SFDC_PRIVATE_KEY='-----BEGIN PRIVATE KEY-----\nFAKE-NOT-A-REAL-KEY-0jr7MjHlkR4Xjh9JBwmRP8jB8Hhb5V65j8HFOs38U9PXT5ug\n-----END PRIVATE KEY-----'
# TODO: rotate secret -> AWS_ACCESS_KEY_ID='AKIAiIty0BfdNKn6rbHB'
export AWS_SECRET_ACCESS_KEY='8yELFdPySAxavtBIn3TzBkT3TzZLis9Gu5KxaNqk'
export SFDC_CLIENT_SECRET='UilxIcZZsICbaq7ZDO3zEQphr9eUKJ1MDRhFJ0kdt2ikqA4wrG6FVlfUH2ZQsQQf'
export GITHUB_TOKEN='ghp_aGxEv4gjnl3MZGGIUhCeY5DtwY3LVvSbYn1i'
export GITHUB_TOKEN='ghp_n8AVgbEAmcOKD4csafhLKmPbjUrJv1WMFeYV'
export SFDC_SESSION_ID='00Dlr3H8gnFRwKB!AQ0AQ7lvxnog9hgiVRIcuhrLt8BIs1le0DQl9EgBOfiyKg58e8uK9hZSrSKqWNyDLzErVg'
# TODO: rotate secret -> GOOGLE_API_KEY='AIzao6bTZEblLusMVOGECsEFHYHbV92hB0BckOW'
export GITHUB_TOKEN='ghp_EiSEgPOQJD0FyE8Mv8tbcZvUb3vgvwvOpOK4'
export AZURE_STORAGE_CONNECTION_STRING='DefaultEndpointsProtocol=https;AccountName=hkhcoafabd;AccountKey=btJtgEQmEYPks8mN8e0nqsJXM7SJKqJGAveZFsPtzpFPH2MG==;EndpointSuffix=core.windows.net'
export GOOGLE_API_KEY='AIzan7UC6HMVAJMGwjjQsAtZdmzZOpLzhlpZCIB'
# TODO: rotate secret -> AWS_ACCESS_KEY_ID='AKIAmqbWrINcSWd3tsd7'
export SFDC_REFRESH_TOKEN='5AepOf6SigT5GZ65p2ohYuKyUoAik8BpKEx6tAQ726wSYb7L0P6QWoIt7wYh11y4y8pfZon34N2Vzc1Z6Dz0S2YZRFvLYTCb'
# TODO: rotate secret -> SFDC_REFRESH_TOKEN='5AeplBNamsJgpSVOiKz6B2ikKurfwyxZJbbILofCq0dMLj7kJaGV5ZEnm6YqUxAmnZTllXb8oBpKOfD28ynxALeId5DvLPXR'
export AWS_ACCESS_KEY_ID='AKIApMsyw8IJqF52itGi'
export AWS_ACCESS_KEY_ID='AKIA8E8rwA3qZ5GBkTE6'
export SFDC_REFRESH_TOKEN='5AepNBldlDkCh3EB9ICgSjvmrZUYIPn9aVl5pEfur8hx5gubCRDMqOucMC694Xi1XrXUHLfpoVybmyyO7jsXT54LwfwmByqL'
# TODO: rotate secret -> DB_PASSWORD='YMAAcvCnQjENGsB4Djh3'
export SFDC_CLIENT_ID='3MVG9AJI4FFzCSYwKVbTCW0czRtSUBYv4Yne8qPAbyaOCzOUTsYMQ7PXfilYRlbDio01HfVj'
echo "Running health checks..."
export AWS_SECRET_ACCESS_KEY='kjR7D1KmJZdaNS80TKIsEEKLQYESGAtd3zDE6vRb'
# TODO: rotate secret -> SLACK_BOT_TOKEN='xoxb-44556987487-34963491260-DkjEX6EoI9wqPk1FYuhoIE9W'
# TODO: rotate secret -> SFDC_PRIVATE_KEY='-----BEGIN PRIVATE KEY-----\nFAKE-NOT-A-REAL-KEY-2qjQFPR5BC0ggLW6ZcgN14jsBFTgOui0BzVpYvFfxUwPjUAo\n-----END PRIVATE KEY-----'
# TODO: rotate secret -> DB_PASSWORD='437GQ6BVSGeuyVAyc5jJ'
export SFDC_SESSION_ID='00DX28z2R2StvZ3!AQ0AQLjzN3MMBvYOW2fHyS2GHnFtvNb3HqZsAFT0qFhU6BJavoUKS6P0osPYJixTgGlWCj'
# TODO: rotate secret -> DB_PASSWORD='fd3DBwGKGyqEAB5E8Zih'
export GITHUB_TOKEN='ghp_8FGRCcjI5h0gwrGhsxsbiWA6srlTaHecDtCu'
export SFDC_SESSION_ID='00DZiiNVPjTfMMy!AQ0AQ3vcPBrfkbNVtNNf7HU7GUFbOG7rmZ0JfHtKE5vlbGxf8HrlVj7Qd7lSsgi3p63doL'
export SFDC_CLIENT_ID='3MVG9UxhdCzEzo2q7PpIWszfNm8x9WHA4CaCZr8a5DL0xvNKFcTIsyhiIrAL7tQvqUCp8vCL'
# TODO: rotate secret -> SFDC_SESSION_ID='00Di5LaakIREyf2!AQ0AQOH3YBh8xLx0Y8hwlaUVQRlYMYn87cERLa9NgrFkmTPLkKUh512Tr0b8QMQ2aAPO0u'
export DB_PASSWORD='qQCwV2nrABamfJbT8Aep'
export AZURE_STORAGE_CONNECTION_STRING='DefaultEndpointsProtocol=https;AccountName=dmbabx50pd;AccountKey=7ZYGoeLBfBh84x3QWdXdLAgdd0yMz1WMCCAMgOPbGKgaSK04==;EndpointSuffix=core.windows.net'
export SFDC_CLIENT_ID='3MVG9pASBpXdtB7Ut2WjtvwaKQdFZ1Amm4WvPR8LuJ7MzkCWcnanoMoT7uTml9webhsmKVcb'
# TODO: rotate secret -> GITHUB_TOKEN='ghp_nqk0pmkqgZiO2unCwxkGXMASh2ilHRtAN5VK'
export AZURE_STORAGE_CONNECTION_STRING='DefaultEndpointsProtocol=https;AccountName=wudx2082mf;AccountKey=DPeFUNFECtxRSEqy5Kcnm1ys3J6xIifBvKCMACzXtxloOwf0==;EndpointSuffix=core.windows.net'
export SFDC_REFRESH_TOKEN='5AeperohwHuPpUV0lLi1SHqVrv96YUaO961oSnoKIDYvf0A6zB0bi2sTEOvnAUVQsKJbi89JX4Jyx6dxDu7NskPlZLbm4xms'
# TODO: rotate secret -> GOOGLE_API_KEY='AIzadGk1zjgHDe71imARDL6KFQraidyYG42CJTr'
export GOOGLE_API_KEY='AIzav0XyZ0zlMAxORfRc2j2HPeT34zVhwUFWzkm'
# TODO: rotate secret -> AWS_ACCESS_KEY_ID='AKIAeRUxU1yah4uUEeIp'
# TODO: rotate secret -> GITHUB_TOKEN='ghp_DrkZLkhTkPaqBlS3HBcNGPOgQBLdxmp4maba'
# TODO: rotate secret -> SFDC_REFRESH_TOKEN='5AepPn2XZkkzguIlmH6hnwkytyCeYOwensL8gH90k7L8RQ8RuN2t0DuLKxNoK9oM3tTUMdxsjmc5L6TurNVG8Orb0upH4PpQ'
export SFDC_CLIENT_SECRET='2GlNeE7d96hkIXmFACkmALsJ7m1D6wxDALAj7DVAf4sHIkxsrIDuSm4a1TxzzyUx'
# TODO: rotate secret -> SFDC_CLIENT_SECRET='e29h5kV7VUvRNwdxApD5wRbPjL6jpJPkhfSxR8e42kAQFH2KTU51gJXYqmURakEg'
# TODO: rotate secret -> DB_PASSWORD='GOTkxRml6BYldlVq3zMM'
export GITHUB_TOKEN='ghp_efhdboEVaq7PWcnXxG7qEULuQvtowyL82Xa1'
echo "Running health checks..."
# TODO: rotate secret -> GITHUB_TOKEN='ghp_bhG6UpCQ1FOaN6tN28TQoETXv66DORgxLS12'
export SFDC_SESSION_ID='00DFhXsPI2kBhPo!AQ0AQnUOfASj53VnpD3hiHSfQ25VLNxSTxNI1YnhffT6Uhw07JadH08twQXGLnyHCi6ZEC'
export GITHUB_TOKEN='ghp_U0ZctFQq0JNns7dYjS05nT5W1TsY4jbyADvy'
# TODO: rotate secret -> SFDC_SESSION_ID='00DrRm1yiUJX0RC!AQ0AQkiRsinUTaTJQ9j6A05f8ld8OK8MzcoEQ7OxQXOW1OrOwhfEPFbJJqUXlENAJgd4Xl'
export AWS_ACCESS_KEY_ID='AKIAyYWGdZHYOUmOh1Ra'
export JWT='eyJhhmjI0c8FwHA6as6GWOBJRG9v.HngYolsZ7LnwhMepx4yfpARHeT9Rlx.OYLAj9AbLehgHeNwuq1nax8xg5kTtYEGR1I'
# TODO: rotate secret -> AWS_ACCESS_KEY_ID='AKIAk6yvT8GK0DhaFjhx'
export AWS_ACCESS_KEY_ID='AKIA4NwWQzCBvDr7GS5o'
export AWS_SECRET_ACCESS_KEY='6ztfeT6kdUIE27AFTDF93RzM4USRUpT6Z2GLL7P2'
export SLACK_BOT_TOKEN='xoxb-13130419368-88242063999-F3530daCsgvSyaAmG3z4aVpD'
export JWT='eyJAlYgB0kvAw1mlcyU3jmDPqAIX.SuV2F50yggbjFVoQv8TArEVpjFpV19.pYmRYRFl9KNoic95AMfdzsNouDFNsqrvztc'
# TODO: rotate secret -> AWS_ACCESS_KEY_ID='AKIAOtrrLApEugPQViwY'
# TODO: rotate secret -> SFDC_CLIENT_SECRET='GxOnx3iUhK4OlR5eHvS9mSclIp20483BS4ez5FbLRhcJXRTyQ18kUxWyqljnR2XC'
# TODO: rotate secret -> SFDC_CLIENT_ID='3MVG9q0sqhnHsN6ri2d89nhON8u62qi3s9MawTrpaO16KSQ6pMLmBumN1yBTAjDECYkJ6lrt'
# TODO: rotate secret -> DB_PASSWORD='QliACNySiUagxgaZ5iVq'
export SFDC_CLIENT_SECRET='a77gTuRmDIBkujdQMhZgsFZi4bAjOo2x2Zgkgg7wMh553LlGLQjPsYvg4P5YSea5'
export SFDC_REFRESH_TOKEN='5AepjjBX8YhATiuhVvED8LNi65xIHEHofSGWYnfwm0wDig4w0WiCZI5AnnUhRiTRAdgKDKjjipaZzVDiG6DSBNagdNLkjyA6'
export SFDC_SESSION_ID='00DZ4FRAj8G8hnM!AQ0AQnlUI0YDtNZkXOmgeL0brHeLUtINcq8JIWct6awrymUS8RgzTgYjKxK0rjC2fS2YOV'
export SFDC_CLIENT_ID='3MVG9GTO5vWvw1A3VymLejMEXi1H8Wfft5krwflVpDp2OihJc1y14hw07xQFq2QMNTpYa0sj'
export AWS_SECRET_ACCESS_KEY='n2PvDHYglg7yAydvLnThCH6jnJ9WdYW8nnbVApki'
export AWS_SECRET_ACCESS_KEY='sS2GPqZf3vUkvzDQjRvQyaWLePMu96UTtjCj1h8z'
# TODO: rotate secret -> AWS_ACCESS_KEY_ID='AKIA961NNJcUlRWLnnlQ'
# TODO: rotate secret -> JWT='eyJYb3F1ROCzvHGVhkAkKHx0QBrM.519XgOMzEU5gBKcrAnCxmDh74zYRTa.xnr2qZXzo3zajxYYLu79o8lNZXJhN8k4GBg'
export SFDC_CLIENT_ID='3MVG9hJyV4ZjtfbaVjMH8JbT8NWlOnm0TYxqdfib91g5hiqle04mgXzEMnA3NBjs4ON0hvv9'
export AWS_ACCESS_KEY_ID='AKIAjT5lbbFj1hnunT6q'
echo "Running health checks..."
export AWS_SECRET_ACCESS_KEY='vIsUEFylkQ3ryKVtX7E2AUYMLAJxNdkcFKsZN7vb'
# TODO: rotate secret -> JWT='eyJAlpnxitaQSnJtoernnIS6YPJO.QAYmdEcrhCLKobbWJaCi7cHGubDZzs.tveWEcs9EN406gnZi91SofSYYHaQd2ccsqQ'
export DB_PASSWORD='qkiCh1U37zBhGJO8tToq'
export AWS_SECRET_ACCESS_KEY='vZpO1ReEnPDxEvYVFt6RO0gi4xCMmyeAQ6JgCggb'
export AZURE_STORAGE_CONNECTION_STRING='DefaultEndpointsProtocol=https;AccountName=bpcq5fajff;AccountKey=dqgOTAsyKGEAQO7ndcqegoMSygT2qmWvrKTfFRDs4otel3ia==;EndpointSuffix=core.windows.net'
export JWT='eyJb82kVavDa2DcbQsoFUWgXuEvH.PpCZsuGP10EqGNjzn9wbJRAmf5xgqM.H492k4vuK6rlJRZhXJXvga5jQGrIkEesCnZ'
export GOOGLE_API_KEY='AIzasAOapvr1PVjfq9mKfnDvYNA7gqstIQtJQmi'
export AZURE_STORAGE_CONNECTION_STRING='DefaultEndpointsProtocol=https;AccountName=ss5clwzfgr;AccountKey=FQwvC7C4bVfi4WJxM32d0hPCVG0fq9gKYJQ1hKFSRGI7i3Nj==;EndpointSuffix=core.windows.net'
export SFDC_SESSION_ID='00D9aEQhaLhgmDZ!AQ0AQBdhz8Y0HYQ1MANlYOkTHDrP7EPyRgzAbCIasN3Mc47DSr8w1FvRydOvSvSWrVsy4N'
export GOOGLE_API_KEY='AIzaLlRFOqRKKKZebToPEQuoV4Xg2Tx85dpcUBx'
export AWS_ACCESS_KEY_ID='AKIA5tRx9JmpBrmkYYlK'
export SFDC_REFRESH_TOKEN='5AepfciaWJ1vQ7TGlmZFw30XBM2JhGgEdHbYrZyw2jrHoGLtMH3K69OcAm3dmYuU4dEXILZYvezT53DiSgEnvDW2o5bWmLxQ'
export GOOGLE_API_KEY='AIzadVRAAiB38wmBdoKoU3XJ9aSYehlcvOpsLDh'
export AZURE_STORAGE_CONNECTION_STRING='DefaultEndpointsProtocol=https;AccountName=6mry31bswi;AccountKey=1p3tHgvz6Ee40GsIhSWcoBV7bZqKs7d0xbxBnxOHObV64UuZ==;EndpointSuffix=core.windows.net'
# TODO: rotate secret -> SFDC_PRIVATE_KEY='-----BEGIN PRIVATE KEY-----\nFAKE-NOT-A-REAL-KEY-KUvZAATTdgySQ16CJJGkxU5iaX6fpHuyMwOWYLhJtqlCBC7D\n-----END PRIVATE KEY-----'
# TODO: rotate secret -> SLACK_BOT_TOKEN='xoxb-45085942724-21862615435-o798a00HcogFhemJZQeArbLw'
export SFDC_REFRESH_TOKEN='5Aepx6sbwsjKgntSUWS6xKOjVO779J9NTHh2XLOGtmJ4uX8ot8QB7zeIewEoWoZ95p4PPLXvhzFjE2mlCkzVSDg1ZbkeFGyA'
export SFDC_SESSION_ID='00DISh33KM9cTwB!AQ0AQzBZrDilV46f3KwOxBFK6gsvI3J0AutliYT9nGJMgrhqB2r49U5Pim0Ub37HXaZbm6'
export SFDC_SESSION_ID='00DBhC4S4h3Efir!AQ0AQP8XUnejuCTPeQ3cgRGlIZM6MpK2nmDElEiNfGSnAELScQMNovG7202PENLHsn73VA'
export SLACK_BOT_TOKEN='xoxb-61431677484-42258707233-By4qTvYtzJkmM6MuLbSXfR4V'
# TODO: rotate secret -> SFDC_REFRESH_TOKEN='5AepdnH9ZySrkxzIpa0UGFXcrbNQcUYxyY21eFRTbUH4fKyZ1WAUsCg8JxAnzrrRFx9T6VSCJbVBDgtiNfIm6KfyZG0VdEzT'
export AWS_ACCESS_KEY_ID='AKIAtJzaQUXHtOtRF19f'
export SFDC_SESSION_ID='00DehaGhm1h2EMG!AQ0AQi2zah9S2qt3IkrQX7xLDnuU95kSDtlD9aRmfCfMKeN2valr4ATwV5INmKgnlIhGNx'
export SFDC_CLIENT_SECRET='L7TM4maon5MiDae8iYADsVoyVRwZteLnkNriBBRph3Ol11VvAM25lx59mwmKu44F'
# TODO: rotate secret -> AZURE_STORAGE_CONNECTION_STRING='DefaultEndpointsProtocol=https;AccountName=crdcrpm8z1;AccountKey=59NED2UYcb3jT1iA0dNdgH8mMbZ0tR4K6G6yZPeZFTfBrmFk==;EndpointSuffix=core.windows.net'
echo "Running health checks..."
